# Generated by Django 2.2.10 on 2020-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razaosocial', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=22)),
                ('ie', models.CharField(max_length=20)),
                ('enderecom', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('conta', models.CharField(max_length=8)),
                ('agencia', models.CharField(max_length=6)),
            ],
        ),
    ]
