# Generated by Django 2.2.10 on 2020-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=40)),
                ('pontoFocalCliente', models.CharField(max_length=40)),
                ('dataIncio', models.DateTimeField(verbose_name='Data de Início')),
                ('dataFim', models.DateTimeField(verbose_name='Data prevista para conclusão')),
                ('gerenteContrato', models.CharField(max_length=40)),
                ('enderecoObra', models.CharField(max_length=100)),
                ('cidadeObra', models.CharField(max_length=100)),
                ('estadoObra', models.CharField(max_length=100)),
                ('cepObra', models.CharField(max_length=9)),
                ('infoGeral', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
