# Generated by Django 2.2.10 on 2020-07-22 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=40)),
                ('pontoFocalCliente', models.CharField(max_length=40)),
                ('dataIncio', models.DateTimeField(verbose_name='Data de Início')),
                ('dataFim', models.DateTimeField(verbose_name='Data prevista para conclusão')),
                ('gerenteContrato', models.CharField(max_length=40)),
                ('enderecoObra', models.CharField(max_length=100)),
                ('cidadeObra', models.CharField(max_length=100)),
                ('estadoObra', models.CharField(max_length=100)),
                ('cepObra', models.CharField(max_length=9)),
                ('infoGeral', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
