# Generated by Django 2.2.10 on 2020-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dataFim',
            field=models.DateField(verbose_name='Data prevista para conclusão'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dataIncio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
    ]
