# Generated by Django 2.2.10 on 2020-07-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataentrega', models.DateField(verbose_name='Data da entrega')),
                ('enderecoentrega', models.CharField(max_length=300)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefoneresponsavel', models.CharField(max_length=12)),
                ('nomedaobra', models.CharField(max_length=100)),
                ('numerooc', models.CharField(max_length=4)),
                ('disciplina', models.CharField(max_length=40)),
                ('revisao', models.CharField(max_length=40)),
                ('referencia', models.CharField(max_length=40)),
                ('data', models.DateTimeField(verbose_name='Data da OC')),
                ('valor', models.CharField(max_length=12)),
                ('DDL', models.CharField(max_length=3)),
                ('datapg', models.DateField(verbose_name='Data de pagamento')),
                ('obs', models.CharField(max_length=50)),
                ('descritivo', models.TextField(max_length=500)),
                ('faturador', models.TextField(max_length=23)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
