# Generated by Django 2.2.10 on 2020-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='faturador',
            field=models.CharField(max_length=23),
        ),
    ]
