# Generated by Django 2.2.10 on 2020-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200728_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da OC'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datapg',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
    ]
